name: stop_watch_timer
description: Simple CountUp timer / CountDown timer. It easily create app of stopwatch.
version: 1.4.0
repository: https://github.com/hukusuke1007/stop_watch_timer
homepage: https://github.com/hukusuke1007/stop_watch_timer

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
